name: ccompilers
version: 0.1.8
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: A set of classes for easy access to the system ะก/ะก++ compilers from the Dart language scripts.
homepage: https://github.com/mezoni/ccompilers
dependencies:
  path: any
